L0: In try-block
L0: In catch-block
$e = >exception 'Exception' with message 'L0 Message' in %s/exception_handling/exception_class_using_conditional_functions.php:133
Stack trace:
#0 {main}<
getMessage:       >L0 Message<
getCode:          >-1<
getPrevious:      ><
getFile:          >%s/exception_handling/exception_class_using_conditional_functions.php<
getLine:          >133<
getTraceAsString: >#0 {main}<
array(0) {
}
Trace Info: none
L0: In finally-block
L0: Beyond try/catch/finally blocks
==========
L0: Calling fL1
fL1: In try-block
fL1: In catch-block
$e = >exception 'Exception' with message 'fL1 Message' in %s/exception_handling/exception_class_using_conditional_functions.php:107
Stack trace:
#0 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#1 {main}<
getMessage:       >fL1 Message<
getCode:          >123<
getPrevious:      ><
getFile:          >%s/exception_handling/exception_class_using_conditional_functions.php<
getLine:          >107<
getTraceAsString: >#0 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#1 {main}<
array(1) {
  [0]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(146)
    ["function"]=>
    string(3) "fL1"
    ["args"]=>
    array(1) {
      [0]=>
      &int(10)
    }
  }
}
Trace Info:
Key[0]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >146<
  Key[function] => >fL1<
  Key[args]:
    Key[0] => >10<
fL1: In finally-block
fL1: Beyond try/catch/finally blocks
==========
fL1: Calling fL2
fL2: In try-block
fL2: In catch-block
$e = >exception 'Exception' with message 'fL2 Message' in %s/exception_handling/exception_class_using_conditional_functions.php:83
Stack trace:
#0 %s/exception_handling/exception_class_using_conditional_functions.php(123): fL2(2.3, -4.5)
#1 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#2 {main}<
getMessage:       >fL2 Message<
getCode:          >234<
getPrevious:      ><
getFile:          >%s/exception_handling/exception_class_using_conditional_functions.php<
getLine:          >83<
getTraceAsString: >#0 %s/exception_handling/exception_class_using_conditional_functions.php(123): fL2(2.3, -4.5)
#1 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#2 {main}<
array(2) {
  [0]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(123)
    ["function"]=>
    string(3) "fL2"
    ["args"]=>
    array(2) {
      [0]=>
      &float(2.3)
      [1]=>
      &float(-4.5)
    }
  }
  [1]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(146)
    ["function"]=>
    string(3) "fL1"
    ["args"]=>
    array(1) {
      [0]=>
      &int(10)
    }
  }
}
Trace Info:
Key[0]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >123<
  Key[function] => >fL2<
  Key[args]:
    Key[0] => >2.3<
    Key[1] => >-4.5<
Key[1]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >146<
  Key[function] => >fL1<
  Key[args]:
    Key[0] => >10<
fL2: In finally-block
fL2: Beyond try/catch/finally blocks
==========
fL2: Calling fL3
fL3: In try-block
fL3: In catch-block
$e = >exception 'Exception' with message 'fL3 Message' in %s/exception_handling/exception_class_using_conditional_functions.php:65
Stack trace:
#0 %s/exception_handling/exception_class_using_conditional_functions.php(99): fL3('xyz', NULL, true)
#1 %s/exception_handling/exception_class_using_conditional_functions.php(123): fL2(2.3, -4.5)
#2 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#3 {main}<
getMessage:       >fL3 Message<
getCode:          >345<
getPrevious:      ><
getFile:          >%s/exception_handling/exception_class_using_conditional_functions.php<
getLine:          >65<
getTraceAsString: >#0 %s/exception_handling/exception_class_using_conditional_functions.php(99): fL3('xyz', NULL, true)
#1 %s/exception_handling/exception_class_using_conditional_functions.php(123): fL2(2.3, -4.5)
#2 %s/exception_handling/exception_class_using_conditional_functions.php(146): fL1(10)
#3 {main}<
array(3) {
  [0]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(99)
    ["function"]=>
    string(3) "fL3"
    ["args"]=>
    array(3) {
      [0]=>
      &string(3) "xyz"
      [1]=>
      &NULL
      [2]=>
      &bool(true)
    }
  }
  [1]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(123)
    ["function"]=>
    string(3) "fL2"
    ["args"]=>
    array(2) {
      [0]=>
      &float(2.3)
      [1]=>
      &float(-4.5)
    }
  }
  [2]=>
  array(4) {
    ["file"]=>
    string(%d) "%s/exception_handling/exception_class_using_conditional_functions.php"
    ["line"]=>
    int(146)
    ["function"]=>
    string(3) "fL1"
    ["args"]=>
    array(1) {
      [0]=>
      &int(10)
    }
  }
}
Trace Info:
Key[0]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >99<
  Key[function] => >fL3<
  Key[args]:
    Key[0] => >xyz<
    Key[1] => ><
    Key[2] => >1<
Key[1]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >123<
  Key[function] => >fL2<
  Key[args]:
    Key[0] => >2.3<
    Key[1] => >-4.5<
Key[2]:
  Key[file] => >%s/exception_handling/exception_class_using_conditional_functions.php<
  Key[line] => >146<
  Key[function] => >fL1<
  Key[args]:
    Key[0] => >10<
fL3: In finally-block
fL3: Beyond try/catch/finally blocks
==========
